export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    description:
      "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    rating: 5,
    image: "link-to-image-1",
    price: 19.99,
    author: "F. Scott Fitzgerald",
    number_of_ratings: 124,
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    description:
      "The story of young girl Scout Finch and her father, lawyer Atticus Finch, as they navigate issues of race and morality.",
    rating: 4,
    image: "link-to-image-2",
    price: 16.95,
    author: "Harper Lee",
    number_of_ratings: 354,
  },
  {
    id: 3,
    title: "1984",
    description:
      "A dystopian social science fiction novel by George Orwell, depicting a totalitarian regime.",
    rating: 5,
    image: "link-to-image-3",
    price: 14.99,
    author: "George Orwell",
    number_of_ratings: 557,
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    description:
      "A novel by J.D. Salinger, following the experiences of a disenchanted teenager named Holden Caulfield.",
    rating: 5,
    image: "link-to-image-4",
    price: 12.49,
    author: "J.D. Salinger",
    number_of_ratings: 87,
  },
  {
    id: 5,
    title: "Harry Potter and the Sorcerer's Stone",
    description:
      "The first book in the Harry Potter series, introducing the young wizard Harry and his adventures at Hogwarts School of Witchcraft and Wizardry.",
    rating: 5,
    image: "link-to-image-5",
    price: 21.99,
    author: "J.K. Rowling",
    number_of_ratings: 414,
  },
  {
    id: 6,
    title: "The Hobbit",
    description:
      "A fantasy novel by J.R.R. Tolkien, following the adventures of Bilbo Baggins as he embarks on a quest to reclaim a treasure guarded by a dragon.",
    rating: 3,
    image: "link-to-image-6",
    price: 18.75,
    author: "J.R.R. Tolkien",
    number_of_ratings: 44,
  },
  {
    id: 7,
    title: "Brave New World",
    description:
      "A dystopian novel by Aldous Huxley, presenting a future society where people are artificially bred and conditioned for a conformist social order.",
    rating: 1,
    image: "link-to-image-7",
    price: 13.99,
    author: "Aldous Huxley",
    number_of_ratings: 44,
  },
  {
    id: 8,
    title: "The Lord of the Rings",
    description:
      "A high-fantasy epic by J.R.R. Tolkien, following the journey to destroy the One Ring and defeat the Dark Lord Sauron.",
    rating: 4,
    image: "link-to-image-8",
    price: 32.5,
    number_of_ratings: 123,
    author: "J.R.R. Tolkien",
  },
  {
    id: 9,
    title: "Fahrenheit 451",
    description:
      "A dystopian novel by Ray Bradbury, depicting a future where books are outlawed and 'firemen' burn any that are found.",
    rating: 5,
    image: "link-to-image-9",
    price: 15.25,
    number_of_ratings: 457,
    author: "Ray Bradbury",
  },
  {
    id: 10,
    title: "The Alchemist",
    description:
      "A novel by Paulo Coelho, following the journey of a shepherd named Santiago as he seeks his 'Personal Legend'.",
    rating: 5,
    image: "link-to-image-10",
    price: 14.99,
    number_of_ratings: 223,
    author: "Paulo Coelho",
  },
  {
    id: 11,
    title: "The Da Vinci Code",
    description:
      "A thriller novel by Dan Brown, centered around a mystery involving symbols, codes, and religious history.",
    rating: 4,
    image: "link-to-image-11",
    price: 11.99,
    number_of_ratings: 444,
    author: "Dan Brown",
  },
  {
    id: 12,
    title: "The Hunger Games",
    description:
      "The first book in a dystopian trilogy by Suzanne Collins, depicting a televised fight to the death in a post-apocalyptic society.",
    rating: 2,
    image: "link-to-image-12",
    price: 14.5,
    number_of_ratings: 784,
    author: "Suzanne Collins",
  },
  {
    id: 13,
    title: "The Road",
    description:
      "A post-apocalyptic novel by Cormac McCarthy, following a father and son as they journey through a devastated America.",
    rating: 1,
    image: "link-to-image-13",
    price: 16.2,
    number_of_ratings: 478,
    author: "Cormac McCarthy",
  },
  {
    id: 14,
    title: "The Kite Runner",
    description:
      "A novel by Khaled Hosseini, exploring themes of guilt, redemption, and the impact of Afghanistan's tumultuous history.",
    rating: 3,
    image: "link-to-image-14",
    price: 13.75,
    number_of_ratings: 342,
    author: "Khaled Hosseini",
  },
  {
    id: 15,
    title: "Pride and Prejudice",
    description:
      "A tale of love and economics among the British upper classes during the early 19th century.",
    rating: 4,
    image: "link-to-image-15",
    price: 12.99,
    number_of_ratings: 557,
    author: "Jane Austen",
  },
];
